version: '3.7'

services:
  php-fpm:
    build:
      dockerfile: Docker/php-fpm/Dockerfile
      context: ./
    volumes:
      - ./Backend:/var/www/html

  nginx:
    image: nginx:stable
    volumes:
#      - ./docker/nginx/default.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public/build/:/var/www/html/public/build:ro
    depends_on:
      - php-fpm
      - db
    ports:
      - "8000:80"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:4.7
      container_name: phpmyadmin
      restart: always
      depends_on:
        - db
      ports:
        - "30002:80"
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: 'password'
      volumes:
        - /sessions

  db:
    container_name: mysql8
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'company-manager'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
