App\Entity\User:
    properties:
        username:
            - NotBlank:
                message: 'Username can not be empty'
            - Length:
                min: 2
                max: 50
                minMessage: 'Too short username, min {{ limit }}'
                maxMessage: 'You have entered too long username, max {{ limit }}'
#            - App\Validator\Constraints\UniqueCredentials: ~
        firstName:
            - NotBlank:
                message: 'First name can not be empty'
            - Length:
                min: 2
                max: 25
                minMessage: 'First name is too short, minimum number is {{ limit }}'
                maxMessage: 'First name is too long, maximum number is {{ limit }}'
            - Regex:
                pattern: '/\d/'
                match: false
                message: 'Your name cannot contain a number'

        lastName:
            - NotBlank:
                message: 'Last name can not be empty'
            - Length:
                min: 2
                max: 50
                minMessage: 'Last name is too short, minimum number is {{ limit }}'
                maxMessage: 'Last name is too long, maximum number is {{ limit }}'
            - Regex:
                pattern: '/\d/'
                match: false
                message: 'Your name cannot contain a number'
        email:
            - NotBlank: ~
#            - App\Validator\Constraints\EmailApi: ~
#            - App\Validator\Constraints\UniqueCredentials: ~